// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTwfJiacu0ovG0APuKICRqHjQHLrSVC2A',
    appId: '1:901597604720:web:3451cf4765e5855aa87db5',
    messagingSenderId: '901597604720',
    projectId: 'expense-tracker-8233f',
    authDomain: 'expense-tracker-8233f.firebaseapp.com',
    storageBucket: 'expense-tracker-8233f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe44_HSbDvzxLM8raCwJcdbtcHYryQfX0',
    appId: '1:901597604720:android:79942d2285f80dd6a87db5',
    messagingSenderId: '901597604720',
    projectId: 'expense-tracker-8233f',
    storageBucket: 'expense-tracker-8233f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz7U6hiGFCM_F25HM4SSmTCp-StLCG9jU',
    appId: '1:901597604720:ios:5e9edf197cd046a8a87db5',
    messagingSenderId: '901597604720',
    projectId: 'expense-tracker-8233f',
    storageBucket: 'expense-tracker-8233f.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz7U6hiGFCM_F25HM4SSmTCp-StLCG9jU',
    appId: '1:901597604720:ios:5e9edf197cd046a8a87db5',
    messagingSenderId: '901597604720',
    projectId: 'expense-tracker-8233f',
    storageBucket: 'expense-tracker-8233f.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTwfJiacu0ovG0APuKICRqHjQHLrSVC2A',
    appId: '1:901597604720:web:0f312392fcbc0414a87db5',
    messagingSenderId: '901597604720',
    projectId: 'expense-tracker-8233f',
    authDomain: 'expense-tracker-8233f.firebaseapp.com',
    storageBucket: 'expense-tracker-8233f.firebasestorage.app',
  );
}
